# Generated by Django 4.2.6 on 2023-10-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='biography',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='character',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='photo_path',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='place_birth',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
